'use strict';
const T=window.Trainer,$=id=>document.getElementById(id);let data,storageOK=true,activeTab='practice';
try{data=T.load(JSON.parse(localStorage.getItem('pocket-practice-v2')),JSON.parse(localStorage.getItem('pocket-practice-v1')));}catch{data=T.defaults();storageOK=false;}
if(!data.round)T.startRound(data,data.selected);
if(!data.session&&data.round.drill==='delivery'&&!data.round.ids.length&&!data.preferences.warmup)T.startRound(data,T.sessionPlan(data)[0].drill);
const current=()=>T.get(data.round.drill),attempts=()=>T.attempts(data),profile=()=>data.round.profile||data.profile;
const mirrored=p=>data.round.mirror?[4-p[0],p[1]]:p;
const fmt=n=>Number(n.toFixed(2)).toString();
function escapeText(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function save(){try{localStorage.setItem('pocket-practice-v2',JSON.stringify(data));storageOK=true;}catch{storageOK=false;}$('storage-note').textContent=storageOK?'Stored on this device. Clearing browser data removes these results.':'Saving is unavailable in this browser. Results will last only while this page stays open.';}
function position(p,radius=null){return T.positionLabel(p,profile(),data.round.mirror,radius);}
function layout(){return T.layout(data.round.drill,data.round.level,profile());}
function draw(){const s=layout(),pr=profile(),canvas=$('table'),ratio=pr.lengthMM?pr.lengthMM/pr.widthMM:2;const w=650,h=Math.round(125*(4*ratio+1.2));canvas.width=w;canvas.height=h;const ctx=canvas.getContext('2d');const scaleY=ratio/2;ctx.scale(125,125);ctx.translate(.6,.6);ctx.scale(1,scaleY);const m=p=>mirrored(p);function circle(p,r,fill,stroke,width=.02){ctx.beginPath();ctx.ellipse(p[0],p[1],r,r/scaleY,0,0,Math.PI*2);if(fill){ctx.fillStyle=fill;ctx.fill();}if(stroke){ctx.strokeStyle=stroke;ctx.lineWidth=width;ctx.stroke();}}function line(points,color,width=.025,dash=[]){ctx.beginPath();points.forEach((p,i)=>i?ctx.lineTo(p[0],p[1]):ctx.moveTo(p[0],p[1]));ctx.strokeStyle=color;ctx.lineWidth=width;ctx.setLineDash(dash);ctx.stroke();ctx.setLineDash([]);}function box(x,y,bw,bh,r,fill){ctx.fillStyle=fill;ctx.beginPath();ctx.roundRect(x,y,bw,bh,r);ctx.fill();}
box(-.35,-.35,4.7,8.7,.24,'#344b4e');box(-.17,-.17,4.34,8.34,.16,'#073f3b');let grad=ctx.createLinearGradient(0,0,4,8);grad.addColorStop(0,'#17877a');grad.addColorStop(1,'#096258');box(0,0,4,8,.09,grad);
ctx.font='.15px sans-serif';ctx.textAlign='center';ctx.textBaseline='middle';for(let x=1;x<4;x++){line([[x,0],[x,8]],'#ffffff12',.013);ctx.fillStyle='#b7c8c8';ctx.fillText(x,x,-.43);for(const y of[-.25,8.25])circle([x,y],.025,'#bbc9c0');}for(let y=1;y<8;y++){line([[0,y],[4,y]],'#ffffff12',.013);ctx.fillStyle='#b7c8c8';ctx.fillText(y,-.46,y);if(y!==4)for(const x of[-.25,4.25])circle([x,y],.025,'#bbc9c0');}
// Rounded jaw shapes indicate the user's pocket style; not measured mouth sizes.
for(const p of[[0,0],[4,0],[0,4],[4,4],[0,8],[4,8]]){circle(p,.19,'#081518');if(p[1]===4){circle([p[0],p[1]-.23],.085,'#0a4943');circle([p[0],p[1]+.23],.085,'#0a4943');}else{circle([p[0]+(p[0]===0?.24:-.24),p[1]],.07,'#0a4943');circle([p[0],p[1]+(p[1]===0?.24:-.24)],.07,'#0a4943');}}
if(s.z){const z=m([s.z.x,s.z.y]);circle(z,s.z.r,'#90deff25','#91ddff',.025);ctx.fillStyle='#b4e9ff';ctx.font='.16px sans-serif';ctx.fillText('TARGET',z[0],z[1]+s.z.r/scaleY+.22);}
if(s.gate){const g=s.gate;line([[g.x-g.half,g.y],[g.x+g.half,g.y]],'#91ddff',.045);for(const x of[g.x-g.half,g.x+g.half])line([[x,g.y-.15],[x,g.y+.15]],'#91ddff',.035);}
if(s.p)circle(m(s.p),.255,null,'#f4c65d',.03);
if(data.round.guide&&s.o){const c=m(s.c),o=m(s.o),p=m(s.p),dx=p[0]-o[0],dy=(p[1]-o[1])*scaleY,d=Math.hypot(dx,dy),separation=2*Math.sqrt(s.ro*s.rc),g=[o[0]-dx/d*separation,o[1]-dy/d*separation/scaleY];line([o,p],'#f4c65d',.025,[.07,.08]);line([c,g],'#ffffffb0',.02,[.06,.075]);circle(g,s.rc,null,'#ffffff9c',.015);}
if(data.round.guide&&s.route){line(s.route.map(m),s.o?'#91ddff':'#ffffff90',.02,[.09,.09]);}
for(const [p,r,color]of[[s.c,s.rc,'#fafbf4'],...(s.o?[[s.o,s.ro,'#f4c65d']]:[])]){const q=m(p);circle([q[0]+.025,q[1]+.035],r+.015,'#023e3988');circle(q,r,color);circle([q[0]-.025,q[1]-.025],.025,'#ffffff88');}
canvas.setAttribute('aria-label',`${current().name}. Cue ball: ${position(s.c,s.rc)}. ${s.o?'Object ball: '+position(s.o)+'. ':''}${current().goal}`);
}
function showTab(name){activeTab=name;for(const n of['practice','drills','progress','settings'])$(n).hidden=n!==name;document.querySelectorAll('nav button').forEach(b=>{b.classList.toggle('active',b.dataset.tab===name);if(b.dataset.tab===name)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});if(name==='settings')fillProfile();window.scrollTo({top:0,behavior:'instant'});}
function fillProfile(){for(const [id,key]of[['object-mm','objectMM'],['cue-mm','cueMM'],['width-mm','widthMM'],['length-mm','lengthMM']])$(id).value=data.profile[key]??'';$('diagram-scale-note').textContent=data.profile.widthMM?'The ball diameters and table proportions use your saved measurements. Pocket mouths remain schematic.':'Until the playing area is measured, the table uses a 2:1 schematic. Ball diameters and target distances shown on it are approximate; no physical table size is inferred from “8 foot”.';}
function renderSession(){const ss=data.session,done=ss?.index===3;$('session-stages').hidden=!ss;$('session-start').hidden=!!ss;$('session-summary').hidden=!done;$('drill-surface').hidden=!!done;
$('warmup').checked=data.preferences.warmup;$('session-focus').value=data.preferences.focus;$('session-options').hidden=!!ss&&ss.index<3;
if(!ss){$('session-heading').textContent='Your 15-shot practice';$('session-description').textContent='A result-led focus, cue-ball control and a pressure finish. Delivery is optional.';return;}
$('session-heading').textContent=done?'Session complete':`Block ${ss.index+1} of 3 · 15 shots in total`;$('session-description').textContent=done?'A clear finish. Keep the result, then come back fresh.':'Five shots per block. Selections use recent results with variety between sessions; each reason is shown below.';
$('session-stages').innerHTML=ss.plan.map((p,i)=>`<div class="stage ${i<ss.index?'complete':i===ss.index?'active':''}"><strong>${String(i+1).padStart(2,'0')} ${p.title||['Focus','Control','Challenge'][i]}</strong>${T.get(p.drill).name}<small>${i===2?'Aim guide off':'5 attempts'}</small><small>${escapeText(p.reason||'Continuing your saved session.')}</small></div>`).join('');
if(done){const ids=(ss.blockIds||[]).flat();const a=data.history.filter(h=>ids.includes(h.id)),goals=a.filter(h=>h.result==='goal').length;$('session-summary').innerHTML=`<p class="eyebrow">PRACTICE COMPLETE</p><h2>${goals} goals from ${a.length} shots.</h2><p>Potting and cue-ball targets both count toward this score.</p>${ss.plan.map((p,i)=>{const shots=a.filter(h=>h.stage===i);return`<div class="summary-row"><span>${T.get(p.drill).name}</span><strong>${shots.filter(h=>h.result==='goal').length} / ${shots.length}</strong></div>`;}).join('')}<button class="primary" id="another-session">Start another session</button> <button class="text-button" id="summary-undo">Undo final shot</button>`;$('another-session').onclick=beginSession;$('summary-undo').onclick=()=>{T.undo(data);data.session.index=2;data.session.blockIds[2]=[];render();};}}
function render(){save();const r=data.round,d=current(),a=attempts(),s=layout(),goals=a.filter(h=>h.result==='goal').length,done=a.length===5,locked=a.length>0;$('table-badge').textContent=`8 ft · ${data.profile.objectMM===50.8&&data.profile.cueMM===50.8?'2″ balls':fmt(data.profile.objectMM)+' mm balls'} · Rounded pockets`;$('practice-mode').textContent=data.session&&data.session.index<3?`Session suggestion: ${data.session.plan[data.session.index].reason||'Continuing your saved session.'}`:'Free practice: your selected drill. Choose another from Drills, or start a suggested session.';$('category').textContent=d.skill;$('title').textContent=d.name;$('difficulty').textContent=`Level ${r.level} / 3`;$('level-name').textContent=d.levels[r.level-1];$('instruction').textContent=d.intro;$('goal').textContent=r.mirror?d.goal.replaceAll('right','left'):d.goal;$('cue-pos').textContent=position(s.c,s.rc);$('object-label').textContent=s.o?'OBJECT BALL':'OBJECT BALLS';$('object-pos').textContent=s.o?position(s.o):'None needed';$('object-legend').hidden=!s.o;$('guide').checked=r.guide;const pressure=r.stage===2&&r.sessionId;$('guide').disabled=!!pressure;$('mirror').disabled=locked||d.kind==='return';$('mirror').textContent=r.mirror?'Original layout':'Mirror layout';$('layout-lock').hidden=!locked;document.querySelectorAll('[data-level]').forEach(b=>{b.classList.toggle('selected',Number(b.dataset.level)===r.level);b.setAttribute('aria-pressed',String(Number(b.dataset.level)===r.level));b.disabled=locked;});
$('coordinate-note').textContent='Diamond spaces: 0–4 across, 0–8 down, from the top-left corner in the diagram. Approximate quarter-diamond positions are enough. Cushion gaps mean the clear space from ball edge to cushion; use an object ball as the unit. For straight drills, line the balls up with the pocket after placing them.';
let target='';if(s.z){const diam=profile().widthMM?profile().objectMM/profile().widthMM*4:.18;const balls=T.fraction(s.z.r*2/diam);target=`White target: ${position([s.z.x,s.z.y],0)}. ${d.id==='stop'?'Radius: one object-ball width.':`Zone is about ${balls} ball-widths across.`} Judge the white’s centre, not its edge.`;}if(s.gate)target=`Return gate: ${position([s.gate.x,s.gate.y],0)}. About ${T.fraction(s.gate.half*2)} diamond spaces wide. Cross between the blue end marks.`;$('target-position').textContent=target;
$('steps').innerHTML=d.steps.map(t=>`<li>${escapeText(r.mirror?t.replaceAll('right','left'):t)}</li>`).join('');$('tip').textContent=d.focus;
let tableTip=d.table;if(d.id==='stop'&&profile().cueMM===profile().objectMM)tableTip='Your white and object balls have equal diameters. Practise a square hit that leaves the white close to the contact point. A small position window makes the result practical to judge.';if(d.id==='follow'&&profile().cueMM===profile().objectMM)tableTip='Your white and object balls are the same size. Calibrate the follow distance on your actual cloth and repeat at the same pace.';$('table-tip').textContent=tableTip;$('ball-note').textContent=`${fmt(profile().objectMM)} mm object balls · ${fmt(profile().cueMM||profile().objectMM)} mm cue ball. No fixed tip offset or power setting is assumed.`;
$('attempts').innerHTML=Array.from({length:5},(_,i)=>`<span class="${a[i]?.result||''}" title="${a[i]?a[i].result==='goal'?'Goal met':a[i].result==='pot'?'Pot only':'Missed':'Not attempted'}"></span>`).join('');$('rep-heading').textContent=done?'Set complete':`Shot ${a.length+1} of 5`;$('score').innerHTML=`${goals}<span>/${a.length}</span>`;
const next=T.recommendation(data);$('feedback').textContent=done?`${goals} of 5 goals. ${next>r.level?'Next time: level '+next+'. '+d.change:next<r.level?'Next time: level '+next+'. Rebuild consistency at a shorter step.':r.level===3&&goals>=4?'Top level held. Try mirroring the next set.':'Keep this level and repeat with one small adjustment.'}`:a.length?`${goals} goals so far. Reset the balls to the same positions.`:d.kind==='control'?'“Pot only” records a successful pot outside the white target. A scratch is always a miss.':d.kind==='return'?'Judge the crossing of the blue gate, not the final resting position.':'Record clean pots without a scratch. Reset after every shot.';if(!storageOK)$('feedback').textContent+=' Saving is unavailable in this browser.';
$('result-buttons').hidden=done;$('continue').hidden=!done;$('continue').textContent=data.session&&r.sessionId===data.session.id?(r.stage===2?'Finish session':'Next block'):`Next set · level ${next}`;$('pot-only').hidden=d.kind!=='control';$('result-buttons').classList.toggle('three',d.kind==='control');$('success').textContent=d.kind==='pot'?'Potted ✓':'Goal met ✓';$('miss').textContent=d.kind==='return'?'Off target':'Missed';$('undo').disabled=!a.length;$('restart').disabled=!a.length;$('mobile-context').textContent=`${d.name} · ${done?'Set complete':`Shot ${a.length+1}/5`} · ${goals} goals${pressure?' · Guide off':''}`;
$('review-last').disabled=$('quick-review').disabled=!a.length;renderSession();renderProgress();draw();}
function choose(id){if(!T.get(id))throw Error('Unknown drill');if(data.session&&data.session.index<3&&!confirm('Leave this session and practise this drill? Your recorded shots will remain in Progress.'))return;data.session=null;T.startRound(data,id);render();showTab('practice');}
function beginSession(){if(data.round.ids.length>0&&data.round.ids.length<5&&!confirm('Start a session? Your recorded shots will remain in Progress.'))return;T.startSession(data);render();showTab('practice');}
function renderProgress(){const total=data.history.length,goals=data.history.filter(h=>h.result==='goal').length,potShots=data.history.filter(h=>T.get(h.drill).kind!=='return'),pots=potShots.filter(h=>h.result!=='miss').length;$('totals').innerHTML=`<div class="stat"><strong>${total}</strong><span>Shots practised</span></div><div class="stat"><strong>${total?Math.round(goals/total*100)+'%':'—'}</strong><span>Goal rate</span></div><div class="stat"><strong>${potShots.length?Math.round(pots/potShots.length*100)+'%':'—'}</strong><span>Pot rate*</span></div>`;
const pattern=ShotCoach.patterns(data.history);$('miss-patterns').innerHTML=`<h2>What your misses look like</h2><p>${pattern.reviewed?pattern.reviewed+' reviewed misses / position misses. These are observations, not proven causes.':'Review a missed shot to start finding patterns. Thin, thick and short misses need different experiments.'}</p>${pattern.counts.map(([key,n])=>`<div class="pattern-row"><span>${escapeText(ShotCoach.labels[key]||key)}</span><strong>${n}</strong></div>`).join('')}`;const rows=T.drills.map(d=>{const a=data.history.filter(h=>h.drill===d.id).slice(-5),g=a.filter(h=>h.result==='goal').length;return{d,a,g};});const needs=rows.filter(v=>v.a.length>=5).sort((a,b)=>a.g-b.g)[0];$('recommendation').innerHTML=`<span>NEXT</span><p>${needs?`A useful repeat: ${needs.d.name}. ${needs.g}/5 goals in your latest attempts.`:'Start a 15-shot session to establish a baseline.'} <small>*Cue-only delivery shots are excluded from pot rate.</small></p>`;
$('progress-list').innerHTML=rows.map(({d,a,g})=>`<div class="progress-row"><button data-progress-drill="${d.id}"><h2>${d.name}</h2><p>${a.length?`${g} goals from ${a.length} recent shots · ${a.map(h=>h.level).every(l=>l===a[0].level)?'Level '+a[0].level:'Mixed levels'}`:'No baseline yet'}</p><small>${d.skill}</small></button><div class="rate">${a.length?g+'/'+a.length:'—'}<small>goals</small></div></div>`).join('');document.querySelectorAll('[data-progress-drill]').forEach(b=>b.onclick=()=>choose(b.dataset.progressDrill));
$('recent-history').innerHTML=data.history.length?data.history.slice(-15).reverse().map(h=>`<div class="recent-row">${T.get(h.drill).name} · ${h.result==='goal'?'Goal met':h.result==='pot'?'Pot only':'Missed'}<small>Level ${h.level} · ${new Date(h.at).toLocaleDateString()}${h.reason?' · '+escapeText(ShotCoach.labels[h.reason]||h.reason):''}</small></div>`).join(''):'<p>No shots recorded yet.</p>';$('legacy-note').textContent=data.legacy.attempts?`Your v1 history is preserved separately: ${data.legacy.pots} pots from ${data.legacy.attempts} attempts. It is not mixed into these new goal scores.`:'';
$('drill-list').innerHTML=T.drills.map((d,i)=>`<button class="drill" data-drill="${d.id}"><span class="number">${String(i+1).padStart(2,'0')} / ${d.skill.toUpperCase()}</span><h2>${d.name}</h2><p>${d.intro}</p><small>${d.advanced?'Advanced · pot + white position':d.kind==='control'?'Pot + white position':d.kind==='return'?'Delivery + return line':'Potting without a scratch'} · 3 levels</small></button>`).join('');document.querySelectorAll('[data-drill]').forEach(b=>b.onclick=()=>choose(b.dataset.drill));}
$('warmup').onchange=e=>{data.preferences.warmup=e.target.checked;save();};$('session-focus').onchange=e=>{data.preferences.focus=e.target.value;save();};$('pick-drill').onclick=()=>showTab('drills');$('session-start').onclick=beginSession;$('success').onclick=()=>{T.record(data,'goal');render();};$('pot-only').onclick=()=>{T.record(data,'pot');render();openReview();};$('miss').onclick=()=>{T.record(data,'miss');render();openReview();};$('undo').onclick=()=>{T.undo(data);render();};$('continue').onclick=()=>{T.nextRound(data);render();window.scrollTo({top:0,behavior:'instant'});};$('restart').onclick=()=>{if(!confirm('Restart this five-shot set? Your recorded attempts will remain in Progress.'))return;const r=data.round;T.startRound(data,r.drill,{...r,profile:undefined});render();};$('mirror').onclick=()=>{if(attempts().length)return;data.round.mirror=!data.round.mirror;render();};$('guide').onchange=e=>{data.round.guide=e.target.checked;render();};document.querySelectorAll('[data-level]').forEach(b=>b.onclick=()=>{if(attempts().length)return;data.round.level=Number(b.dataset.level);render();});document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>showTab(b.dataset.tab));document.querySelectorAll('[data-open-table]').forEach(b=>b.onclick=()=>showTab('settings'));document.querySelector('.brand').onclick=e=>{e.preventDefault();showTab('practice');};
$('profile-form').onsubmit=e=>{e.preventDefault();try{const p=T.validateProfile({objectMM:$('object-mm').value,cueMM:$('cue-mm').value,widthMM:$('width-mm').value,lengthMM:$('length-mm').value});data.profile=p;if(!attempts().length)data.round.profile=JSON.parse(JSON.stringify(p));$('profile-message').textContent=attempts().length?'Saved. The current set keeps its original setup; the next set uses these measurements.':'Saved. Your diagrams now use this setup.';render();fillProfile();}catch(err){$('profile-message').textContent=err.message;}};
let reviewId=null;
function reviewedShot(){return data.history.find(h=>h.id===reviewId);}
function openReview(){const shot=attempts().at(-1);if(!shot)return;reviewId=shot.id;const d=T.get(shot.drill),opts=ShotCoach.options(d,shot.result);$('reason').innerHTML='<option value="">Choose what you observed</option>'+opts.map(v=>`<option value="${v}">${escapeText(ShotCoach.labels[v])}</option>`).join('');$('reason').value=opts.includes(shot.reason)?shot.reason:'';const c=ShotCoach.context(shot.context);$('shot-pace').value=c.pace;$('shot-impact').value=c.impact;$('shot-side').value=c.side;$('shot-context').hidden=d.kind==='return';$('review-shot-label').textContent=`${d.name} · Level ${shot.level} · ${shot.result==='goal'?'Goal met':shot.result==='pot'?'Potted, position missed':'Missed'}`;renderCoach();$('shot-review').showModal();}
function renderCoach(){const shot=reviewedShot();if(!shot)return;const d=T.get(shot.drill),p=shot.profile||data.profile,lay=T.layout(shot.drill,shot.level,p),angle=ShotCoach.cutAngle(lay,p),advice=ShotCoach.analyse(shot,d,angle);$('coach-advice').innerHTML=`<p class="eyebrow">POSSIBLE EXPLANATION</p><h3>${escapeText(advice.title)}</h3><p>${escapeText(advice.why)}</p>${advice.throwNote?`<p class="throw-note">${escapeText(advice.throwNote)}</p>`:''}<div class="next-shot"><span>ON YOUR NEXT SHOT</span><p>${escapeText(advice.test)}</p><small>${escapeText(advice.hold)}</small></div>`;}
function updateReview(){const shot=reviewedShot();if(!shot)return;shot.reason=$('reason').value||null;shot.context=ShotCoach.context({pace:$('shot-pace').value,impact:$('shot-impact').value,side:$('shot-side').value});save();renderCoach();renderProgress();}
$('reason').onchange=updateReview;for(const id of['shot-pace','shot-impact','shot-side'])$(id).onchange=updateReview;
$('review-last').onclick=$('quick-review').onclick=openReview;$('close-review').onclick=$('review-done').onclick=()=>{$('shot-review').close();};
render();
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'start_pool_drill',description:'Start a five-shot fundamental pool drill. Fails if it would replace an unfinished set or session.',inputSchema:{type:'object',properties:{drill_id:{type:'string',enum:T.drills.map(d=>d.id)}},required:['drill_id'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(!input||!T.get(input.drill_id))throw Error('Unknown drill.');if((attempts().length>0&&attempts().length<5)||(data.session&&data.session.index<3))throw Error('Finish or leave the current set in the app first.');data.session=null;T.startRound(data,input.drill_id);render();showTab('practice');return{drill:current().name,level:data.round.level,goal:current().goal};}})).catch(()=>{});}catch{}}
