/* Observation-led coaching. Suggestions are hypotheses, never measured diagnoses. */
(function(root){'use strict';
const labels={thick:'Too thick / undercut',thin:'Too thin / overcut',object_short:'Object ball stopped before the pocket',jaws:'Object ball rattled out',short:'White finished short of its target',long:'White travelled beyond its target',forward:'White rolled forward after contact',back:'White came back after contact',left:'Missed left of the intended line',right:'Missed right of the intended line',scratch:'White went in a pocket',unknown:'Not sure what happened',clean:'Clean pot / target met',made_jaws:'Made it, but caught a jaw'};
const contextDefaults=()=>({pace:'unknown',impact:'unknown',side:'unknown'});
function context(raw){const r=raw||{};return{pace:['slow','medium','firm'].includes(r.pace)?r.pace:'unknown',impact:['roll','stun','draw'].includes(r.impact)?r.impact:'unknown',side:['none','inside','outside','unintended'].includes(r.side)?r.side:'unknown'};}
function options(drill,result){if(result==='goal')return drill.kind==='return'?['clean','unknown']:['clean','made_jaws','unknown'];if(drill.kind==='return')return['left','right','short','unknown'];if(result==='pot')return drill.id==='stop'?['forward','back','left','right','unknown']:['short','long','left','right','unknown'];return['thick','thin','object_short','jaws','scratch','unknown'];}
function cutAngle(layout,profile){if(!layout.o)return 0;const k=profile?.lengthMM?profile.lengthMM/profile.widthMM/2:1;const n=[layout.p[0]-layout.o[0],(layout.p[1]-layout.o[1])*k],len=Math.hypot(...n),unit=n.map(x=>x/len);const sep=2*Math.sqrt(layout.ro*layout.rc);const g=[layout.o[0]-unit[0]*sep,layout.o[1]-unit[1]*sep/k];const v=[g[0]-layout.c[0],(g[1]-layout.c[1])*k];return Math.acos(Math.min(1,Math.max(-1,(v[0]*unit[0]+v[1]*unit[1])/Math.hypot(...v))))*180/Math.PI;}
function analyse(shot,drill,angle){const r=shot.reason||'unknown',c=context(shot.context),cut=angle>3;let title='Observe before changing the shot',why='A result alone cannot separate aim, delivery, pace and spin.',test='Repeat the exact setup. Watch the object-ball line first, then the white. Record the first thing that went wrong.',hold='Keep the layout, pace and intended spin the same.',throwNote='';
if(shot.result==='goal'){title='Keep the recipe that worked';why='A make tells you the outcome worked, not which part of your technique caused it.';test='Repeat with the same routine and record pace and spin. Three clean repeats are more useful evidence than one make.';if(r==='made_jaws'){title='A make with little margin';why='Catching a rounded jaw can hide an entry-line or pace error.';test='Keep the same pace and aim for a cleaner entry on the next repeat. Do not count this as proof of a reliable pocket line.';}}
else if(r==='object_short'){title='Test a little more pace';why='If the object ball stayed on the pocket line but stopped early, insufficient travel is the first thing to test. Contact thickness also changes transferred speed.';test='Keep the aim and tip contact unchanged. Increase pace slightly for the next repeat; do not also change the cut.';hold='Same setup, aiming line and tip contact.';}
else if(r==='jaws'){title='Check entry line before blaming power';why='On rounded pockets, both the arrival line and pace can reject a ball. A rattle does not prove you hit too hard.';test='Repeat the same aiming line at a slightly gentler pace. If it still catches the same jaw, restore the original pace and test a small line adjustment in a separate repeat.';hold='Change only pace first; keep side spin out of the comparison.';}
else if(r==='thick'){title=cut?'Fuller contact or throw?':'Recheck the straight setup';why=cut?'An undercut can come from a fuller-than-needed hit or from a change in the object ball’s path during contact. Your report cannot tell these apart.':'This layout is essentially straight. Ordinary cut-induced throw is not the first explanation; check that the balls and pocket actually line up.';test=cut?'Keep pace and spin unchanged. Aim a little thinner for the next repeat and compare the object-ball line. Treat this as an aiming adjustment, not proof of throw.':'Rebuild the line while standing. Use no intentional side spin and repeat the same stroke.';hold='Same ball positions, pace and spin; change only the aim.';}
else if(r==='thin'){title=cut?'Start with a slightly fuller hit':'Check alignment and unintended side';why=cut?'An overcut can come from a thin hit or too much allowance for throw. Ordinary cut-induced throw alone tends toward undercut, so it does not explain a thin miss.':'A nominally straight shot has no meaningful thick/thin cut to diagnose. Recheck the setup and watch for sideways delivery.';test=cut?'Keep pace and spin unchanged. Aim slightly fuller on the next repeat. Do not automatically add side spin.':'Keep the same pace, use centre-line tip contact and rebuild the straight setup.';hold='Change the aiming line only.';}
else if(r==='short'&&drill.id==='draw'){title='Too little draw distance—not necessarily too little power';why='Backspin may have worn off before contact, or the delivered low contact may differ from your intention. Cloth and speed both matter.';test='Keep the pace unchanged and test a slightly lower, well-chalked tip contact with a level cue. If the white still rolls forward, shorten the approach in the next set to establish reliable draw.';hold='Same layout and pace. Stay comfortably inside the miscue limit.';}
else if(r==='long'&&drill.id==='draw'){title='Calibrate the screw-back distance';why='The white came back farther than the target. Pace, backspin and contact quality can all alter that distance.';test='Keep the same tip contact and aim; reduce pace slightly. Check the result before changing tip height.';hold='Same setup and low contact.';}
else if(r==='forward'&&drill.id==='stop'){title='The white retained forward roll';why='On a square hit with your equal-size balls, forward travel is consistent with topspin remaining at impact. An off-centre collision can also leave motion.';test='At the same pace, try a slightly lower tip contact. Confirm the object ball still travels on the straight line.';hold='Change tip height only; keep the same distance and pace.';}
else if(r==='back'&&drill.id==='stop'){title='Some backspin may have remained';why='With your equal-size balls, a clear screw-back on a square hit suggests backspin at contact. Very small recoil alone is not a precise spin measurement.';test='Keep the pace and aim the same; move the tip contact slightly toward centre for the next attempt.';hold='Change tip height only.';}
else if(r==='short'||r==='long'){title=r==='short'?'Check whether pace is the missing piece':'Test a little less travel';why=drill.kind==='return'?'If the white never reached the return gate, the shot lacked enough travel for this drill. A sideways return is a separate issue.':'A position miss can reflect pace, spin or contact thickness. It does not by itself prove a power error.';test=drill.id==='follow'?(r==='short'?'If the white was rolling forward cleanly after the pot, keep the same high contact and add a little pace.':'Keep the same high contact and reduce pace slightly.'):r==='short'?'Keep the same aiming line and tip contact and add a little pace.':'Keep the same aiming line and tip contact and reduce pace slightly.';hold='Same setup and tip contact; change only pace.';}
else if(r==='left'||r==='right'){title=drill.kind==='return'?'Check the return line':'Watch where the error first appears';why=drill.kind==='return'?'Alignment, unintended side spin and cushion or cloth bias can all move the return. One miss cannot identify which.':'Left/right from your viewpoint does not establish thick/thin. The object ball and white also have different intended paths.';test=drill.kind==='return'?'Repeat once with the same setup and no intended side spin. Then compare from the other end at the same pace; a persistent table-direction bias deserves a table check.':'On the next repeat, watch whether the object ball misses first or the white misses its target after a good pot. Log that specific outcome.';}
else if(r==='scratch'){title='Separate potting from cue-ball route';why='A potted white can come from the chosen angle and spin even when the object ball was aimed correctly.';test='Before the next shot, trace the intended white route. Keep the object-ball aim fixed and test a small change in forward/back spin appropriate to this drill.';hold='Do not change aim and spin together. A scratch remains a miss.';}
if(cut&&shot.result!=='goal'){
throwNote='Cut-induced throw comes from friction during ball contact and can make the object ball take a fuller line. It is not measured by this app.';
if(c.side==='inside'||c.side==='outside'||c.side==='unintended'){throwNote='Side spin can change both the cue-ball approach (deflection and swerve) and object-ball throw. Do not label this miss as cut-induced throw alone.';if(r==='thick'||r==='thin'){title='First separate side-spin effects';test='Use the same pace and centre-line tip contact with no intended side spin for a comparison shot. Rebuild the no-side aiming line rather than carrying over a side-spin allowance.';hold='Keep layout and pace fixed; compare with no side spin.';}}
else if(r==='thick'&&c.pace==='slow'&&c.impact==='stun'&&c.side==='none'){title='Throw is worth testing here';throwNote=angle>=20&&angle<=40?'This layout is near the half-ball range. Slow stun with no side spin is a condition where cut-induced throw can be pronounced.':'Slow stun makes throw worth considering, although this layout is outside the half-ball range where it is typically strongest.';test='Keep the same pace and spin; test a slightly thinner aim. If the repeated full-line miss reduces, you have a useful compensation—not proof that throw was the only cause.';}
else if(c.impact==='roll'||c.impact==='draw')throwNote='At comparable impact speed, rolling or backspinning contact generally produces less cut-induced throw than stun. It does not eliminate throw or rule out an aiming error.';
}
if(!cut&&drill.kind!=='return')throwNote='This is a near-straight layout. Do not infer cut-induced throw from the miss. Unintended side spin is a separate possibility.';
return{title,why,test,hold,throwNote,context:c};}
function patterns(history){const reviewed=history.filter(h=>h.reason&&h.reason!=='unknown'&&h.result!=='goal');const counts={};for(const h of reviewed)counts[h.reason]=(counts[h.reason]||0)+1;return{reviewed:reviewed.length,counts:Object.entries(counts).sort((a,b)=>b[1]-a[1]).slice(0,3)};}
const api={labels,contextDefaults,context,options,cutAngle,analyse,patterns};if(typeof module!=='undefined')module.exports=api;else root.ShotCoach=api;
})(typeof window!=='undefined'?window:globalThis);
