/* Pure practice model; shared by the interface and validation. */
(function(root){
'use strict';
const drills=[
{id:'delivery',name:'Return to the line',skill:'Cue delivery',kind:'return',intro:'Send the white up the centre of the table and back.',steps:['Place only the cue ball at the marked starting point. Aim squarely at the middle of the top cushion.','Use centre ball, a level cue and enough pace for the white to return past its starting line. Move the cue clear after the stroke.','Judge where the centre of the white crosses the starting line on its return. Reset after every shot.'],goal:'The white returns through the marked gate. Its final stopping point does not matter.',focus:'Keep the same bridge, pause and finish on every delivery.',table:'A cushion or cloth bias can also move the return. Compare from the other end before blaming your stroke.',levels:['Wide gate','Medium gate','Narrow gate'],change:'The return gate gets narrower.'},
{id:'straight-v2',name:'Straight-pot ladder',skill:'Potting & alignment',kind:'pot',intro:'Keep the line. Gradually add distance.',steps:['Use one red or yellow. Put its centre on the line from the cue ball to the highlighted corner.','Stand behind that line, choose the pocket entry, then step into your stance.','Pot at a comfortable pace. Reset to the same positions for all five attempts.'],goal:'Pot the object ball without potting the white. Rebuild your routine before every attempt.',focus:'Watch the object ball enter the pocket before standing up.',table:'Aim for a clean entry through the rounded jaws. Record jaw rattles as misses; do not count a near-pot.',levels:['Short','Medium','Long'],change:'Both balls move farther from the corner.'},
{id:'stop',name:'Stop in the window',skill:'Stun control',kind:'control',intro:'Pot the ball and leave the white close to contact.',steps:['Set a straight shot into the highlighted corner. The blue circle surrounds the cue-ball contact position.','Start with a modest below-centre strike. Adjust pace and tip height until forward roll has worn off at impact.','Judge the white only when it has stopped. Record “Pot only” if the pot goes in but the white leaves the target.'],goal:'Pot the object ball, with the white’s centre finishing inside the blue circle and no scratch.',focus:'Change one thing at a time: tip height or pace, then repeat.',table:'With a smaller, lighter white, some recoil can occur. This is a practical position window, not a test of a mathematically dead stop.',levels:['Short approach','Longer approach','Long approach'],change:'The cue-ball approach gets longer; the position window stays the same.'},
{id:'follow',name:'Follow to a landing zone',skill:'Follow control',kind:'control',intro:'Pot, then roll the white forward to a chosen spot.',steps:['Set a straight shot. The blue zone is beyond the object ball toward the pocket.','Strike above centre with no intentional side spin. Begin softly and adjust your pace.','Keep the same ball positions and target for the full set. A potted white is always a miss.'],goal:'Pot the object ball and stop the white’s centre inside the blue target.',focus:'Judge travel after contact. More power is not the same as better control.',table:'Learn this distance on your own cloth and ball set. A smaller, lighter white will not follow like an equal-weight white.',levels:['Short roll','Medium roll','Longer roll'],change:'The target moves farther beyond the object ball.'},
{id:'draw',name:'Screw back to a target',skill:'Draw control',kind:'control',intro:'Bring the white back a useful, repeatable distance.',steps:['Set a straight shot. The blue target is behind the cue-ball contact position.','Chalk, use a level cue and a controlled below-centre strike. Start with the shortest target.','Pot the object ball and bring the white back into the zone. Reset both balls after each attempt.'],goal:'Pot the object ball and stop the white’s centre inside the blue target, without a scratch.',focus:'A repeatable low contact and smooth delivery matter more than forcing the shot.',table:'Backspin loss depends on your cloth and the travel to the object ball. Calibrate by outcome rather than a fixed power percentage.',levels:['Short screw','Medium screw','Longer screw'],change:'The return target moves farther back.'},
{id:'cuts',name:'Cut-angle ladder',skill:'Cut potting',kind:'pot',intro:'Learn the pocket from three approach angles.',steps:['Keep the object ball in its marked position. Place the white at the selected level.','Choose the object-ball path into the pocket before getting down on the shot. Use no intentional side spin.','Play five repetitions, then use the mirrored layout for the other side.'],goal:'Pot through the highlighted corner without scratching. A jaw rattle that stays out is a miss.',focus:'Separate a line error from a pace error. Do not change both together.',table:'Rounded jaws make the real entry line important. The dashed line is a reference, not an exact pocket-acceptance prediction.',levels:['Gentle cut','Medium cut','Thinner cut'],change:'The cue ball moves sideways to increase the cut.'},
{id:'rail-v2',name:'Cushion-side potting',skill:'Rounded-pocket touch',kind:'pot',intro:'Find a reliable entry near the long cushion.',steps:['Place the object ball near, but not touching, the right cushion. Follow the grid rather than pressing it against the rail.','Use centre ball and a measured pace. Aim at the opening between the rounded jaws.','Reset both balls to the same gap from the cushion. Change only the distance when progressing.'],goal:'Pot into the highlighted corner with no scratch. Count a rejected jaw rattle as a miss.',focus:'Keep the delivery straight; avoid adding side spin to rescue the line.',table:'The diagram does not model your exact jaw opening or pocket shelf. Let clean entries on your table set the pace.',levels:['Short rail shot','Medium rail shot','Long rail shot'],change:'The object ball and cue ball move farther up the cushion.'},
{id:'side-v2',name:'Middle-pocket touch',skill:'Pocket entry',kind:'pot',intro:'Approach the middle pocket from widening angles.',steps:['Set one object ball by the marked middle-pocket approach. Use the cue-ball position for your level.','Choose a positive but controlled pace and no intentional side spin.','Keep the same positions for five shots. Mirror the next set to train the other middle pocket.'],goal:'Pot in the highlighted middle pocket without a scratch. Potting elsewhere does not count.',focus:'Do not assume the whole visible opening is available from an angle.',table:'Your rounded middle-pocket jaws need their own speed and entry-line practice; these are not American-style pocket targets.',levels:['Near square','Oblique','More oblique'],change:'The approach to the middle pocket becomes more oblique.'}
];
const defaults=()=>({version:2,selected:'delivery',profile:{objectMM:50.8,cueMM:50.8,widthMM:null,lengthMM:null},levels:{},round:null,history:[],session:null,sessionCount:0,legacy:{attempts:0,pots:0}});
const get=id=>drills.find(d=>d.id===id);
function validateProfile(p){const num=v=>v===''||v==null?null:Number(v);const out={objectMM:num(p.objectMM),cueMM:num(p.cueMM),widthMM:num(p.widthMM),lengthMM:num(p.lengthMM)};if(!Number.isFinite(out.objectMM)||out.objectMM<45||out.objectMM>60)throw Error('Object-ball diameter must be 45–60 mm.');if(out.cueMM!==null&&(!Number.isFinite(out.cueMM)||out.cueMM<40||out.cueMM>60))throw Error('Cue-ball diameter must be 40–60 mm.');if((out.widthMM===null)!==(out.lengthMM===null))throw Error('Enter both playing dimensions, or leave both blank.');if(out.widthMM!==null&&(!Number.isFinite(out.widthMM)||!Number.isFinite(out.lengthMM)||out.widthMM<800||out.widthMM>1400||out.lengthMM<1600||out.lengthMM>2800||out.lengthMM/out.widthMM<1.8||out.lengthMM/out.widthMM>2.2))throw Error('Check the cushion-nose measurements in mm; the length should be about twice the width.');return out;}
function load(raw,legacy){const d=defaults();if(!raw){if(legacy?.history){d.legacy={attempts:legacy.history.filter(h=>typeof h.pot==='boolean').length,pots:legacy.history.filter(h=>h.pot===true).length};}return d;}try{const p=validateProfile(raw.profile);d.profile=p;d.selected=get(raw.selected)?raw.selected:'delivery';d.levels=Object.fromEntries(drills.map(x=>[x.id,Math.min(3,Math.max(1,Number(raw.levels?.[x.id])||1))]));d.history=Array.isArray(raw.history)?raw.history.filter(h=>h&&get(h.drill)&&['goal','pot','miss'].includes(h.result)&&typeof h.id==='string'):[];d.legacy=raw.legacy||d.legacy;d.sessionCount=Number(raw.sessionCount)||0;if(raw.round&&get(raw.round.drill)&&Array.isArray(raw.round.ids)&&raw.round.ids.length<=5&&raw.round.ids.every(id=>d.history.some(h=>h.id===id))){d.round=raw.round;d.selected=raw.round.drill;}if(raw.session&&Array.isArray(raw.session.plan)&&raw.session.plan.length===3&&raw.session.plan.every(x=>get(x.drill))&&Number.isInteger(raw.session.index)&&raw.session.index>=0&&raw.session.index<=3)d.session=raw.session;return d;}catch{return d;}}
function startRound(d,id,options={}){if(!get(id))throw Error('Unknown drill.');const level=options.level??d.levels[id]??1;if(!Number.isInteger(level)||level<1||level>3)throw Error('Level must be 1, 2 or 3.');d.selected=id;d.round={drill:id,level,mirror:!!options.mirror,guide:options.guide!==false,ids:[],sessionId:options.sessionId||null,stage:options.stage??null,profile:JSON.parse(JSON.stringify(d.profile))};return d.round;}
function attempts(d){return d.round?d.round.ids.map(id=>d.history.find(h=>h.id===id)).filter(Boolean):[];}
function recommendation(d){const r=d.round,a=attempts(d),goals=a.filter(h=>h.result==='goal').length;if(a.length<5)return r.level;return Math.min(3,Math.max(1,r.level+(goals>=4?1:goals<=1?-1:0)));}
function record(d,result){const r=d.round;if(!r||r.ids.length>=5)throw Error('This set is complete.');if(!['goal','pot','miss'].includes(result)||(result==='pot'&&get(r.drill).kind!=='control'))throw Error('Invalid result for this drill.');const id=Date.now().toString(36)+'-'+Math.random().toString(36).slice(2);d.history.push({id,drill:r.drill,level:r.level,mirror:r.mirror,result,at:Date.now(),sessionId:r.sessionId,stage:r.stage,profile:r.profile,reason:null});r.ids.push(id);return id;}
function undo(d){if(!d.round?.ids.length)return false;const id=d.round.ids.pop();d.history=d.history.filter(h=>h.id!==id);return true;}
function nextRound(d){if(attempts(d).length!==5)throw Error('Finish this set first.');const r=d.round;d.levels[r.drill]=recommendation(d);if(d.session&&r.sessionId===d.session.id){d.session.blockIds=d.session.blockIds||[[],[],[]];d.session.blockIds[r.stage]=r.ids.slice();d.session.index++;if(d.session.index===3)return false;const p=d.session.plan[d.session.index];startRound(d,p.drill,{...p,sessionId:d.session.id,stage:d.session.index});return true;}startRound(d,r.drill,{level:d.levels[r.drill],mirror:r.mirror,guide:r.guide});return true;}
function startSession(d){const controls=['stop','follow','draw'];const unseen=controls.find(id=>!d.history.some(h=>h.drill===id));let control=unseen;if(!control)control=controls.map(id=>{const a=d.history.filter(h=>h.drill===id).slice(-10);return{id,rate:a.filter(h=>h.result==='goal').length/a.length};}).sort((a,b)=>a.rate-b.rate)[0].id;const pots=['straight-v2','cuts','rail-v2','side-v2'];const pot=pots[d.sessionCount%pots.length];const n=d.sessionCount++;d.session={id:'session-'+Date.now(),index:0,blockIds:[[],[],[]],plan:[{drill:'delivery',guide:true,mirror:false},{drill:control,guide:true,mirror:!!(n%2)},{drill:pot,guide:false,mirror:!!(n%2)}]};startRound(d,'delivery',{...d.session.plan[0],sessionId:d.session.id,stage:0});}
function layout(id,level,profile){const d=get(id);if(!d||!Number.isInteger(level)||level<1||level>3)throw Error('Invalid layout.');const ro=profile.widthMM?profile.objectMM/profile.widthMM*2:.09,rc=ro*(profile.cueMM||profile.objectMM)/profile.objectMM,gap=2*Math.sqrt(ro*rc),p=[4,0],ky=profile.lengthMM?profile.lengthMM/profile.widthMM/2:1,den=Math.hypot(1,2*ky),u=[-1/den,2/den];let o,c,z=null,gate=null,route=null;
if(id==='delivery'){c=[2,6];gate={x:2,y:6,half:[.6,.4,.22][level-1]};route=[c,[2,rc],[2,6.5]];return{c,o:null,p:null,z,gate,route,ro,rc};}
if(id==='straight-v2'){o=[4-[.7,1.1,1.5][level-1],[1.4,2.2,3][level-1]];c=[o[0]-.55*level,o[1]+1.1*level];}
if(['stop','follow','draw'].includes(id)){o=[2.5,3];const distance=id==='stop'?[1.2,2.3,3.4][level-1]:1.5;c=[o[0]+u[0]*distance,o[1]+u[1]*distance];const contact=[o[0]+u[0]*gap,o[1]+u[1]*gap];const travel=id==='stop'?0:(id==='follow'?-1:1)*[.65,1.1,1.6][level-1];z={x:contact[0]+u[0]*travel,y:contact[1]+u[1]*travel,r:id==='stop'?ro*2:[.45,.4,.35][level-1]};}
if(id==='cuts'){o=[2.8,2.4];c=[[1.4,5.8],[.8,4.6],[.7,3.1]][level-1];}
if(id==='rail-v2'){o=[3.65,[1.8,2.8,3.8][level-1]];c=[3.2,o[1]+2];}
if(id==='side-v2'){o=[[2.8,4.15],[2.8,4.5],[2.8,4.9]][level-1];c=[1,5.8];p[1]=4;}
return{c,o,p,z,gate,route,ro,rc};}
const api={drills,defaults,get,load,validateProfile,startRound,attempts,recommendation,record,undo,nextRound,startSession,layout};if(typeof module!=='undefined')module.exports=api;else root.Trainer=api;
})(typeof window!=='undefined'?window:globalThis);
