/* Pure practice model; shared by the interface and validation. */
(function(root){
'use strict';
const drills=[
{id:'delivery',name:'Return to the line',skill:'Cue delivery',kind:'return',intro:'Send the white up the centre of the table and back.',steps:['Place only the cue ball at the marked starting point. Aim squarely at the middle of the top cushion.','Use centre ball, a level cue and enough pace for the white to return past its starting line. Move the cue clear after the stroke.','Judge where the centre of the white crosses the starting line on its return. Reset after every shot.'],goal:'The white returns through the marked gate. Its final stopping point does not matter.',focus:'Keep the same bridge, pause and finish on every delivery.',table:'A cushion or cloth bias can also move the return. Compare from the other end before blaming your stroke.',levels:['Wide gate','Medium gate','Narrow gate'],change:'The return gate gets narrower.'},
{id:'straight-v2',name:'Straight-pot ladder',skill:'Potting & alignment',kind:'pot',intro:'Keep the line. Gradually add distance.',steps:['Use one red or yellow. Put its centre on the line from the cue ball to the highlighted corner.','Stand behind that line, choose the pocket entry, then step into your stance.','Pot at a comfortable pace. Reset to the same positions for all five attempts.'],goal:'Pot the object ball without potting the white. Rebuild your routine before every attempt.',focus:'Watch the object ball enter the pocket before standing up.',table:'Aim for a clean entry through the rounded jaws. Record jaw rattles as misses; do not count a near-pot.',levels:['Short','Medium','Long'],change:'Both balls move farther from the corner.'},
{id:'stop',name:'Stop in the window',skill:'Stun control',kind:'control',intro:'Pot the ball and leave the white close to contact.',steps:['Set a straight shot into the highlighted corner. The blue circle surrounds the cue-ball contact position.','Start with a modest below-centre strike. Adjust pace and tip height until forward roll has worn off at impact.','Judge the white only when it has stopped. Record “Pot only” if the pot goes in but the white leaves the target.'],goal:'Pot the object ball, with the white’s centre finishing inside the blue circle and no scratch.',focus:'Change one thing at a time: tip height or pace, then repeat.',table:'With a smaller, lighter white, some recoil can occur. This is a practical position window, not a test of a mathematically dead stop.',levels:['Short approach','Longer approach','Long approach'],change:'The cue-ball approach gets longer; the position window stays the same.'},
{id:'follow',name:'Follow to a landing zone',skill:'Follow control',kind:'control',intro:'Pot, then roll the white forward to a chosen spot.',steps:['Set a straight shot. The blue zone is beyond the object ball toward the pocket.','Strike above centre with no intentional side spin. Begin softly and adjust your pace.','Keep the same ball positions and target for the full set. A potted white is always a miss.'],goal:'Pot the object ball and stop the white’s centre inside the blue target.',focus:'Judge travel after contact. More power is not the same as better control.',table:'Learn this distance on your own cloth and ball set. A smaller, lighter white will not follow like an equal-weight white.',levels:['Short roll','Medium roll','Longer roll'],change:'The target moves farther beyond the object ball.'},
{id:'draw',name:'Screw back to a target',skill:'Draw control',kind:'control',intro:'Bring the white back a useful, repeatable distance.',steps:['Set a straight shot. The blue target is behind the cue-ball contact position.','Chalk, use a level cue and a controlled below-centre strike. Start with the shortest target.','Pot the object ball and bring the white back into the zone. Reset both balls after each attempt.'],goal:'Pot the object ball and stop the white’s centre inside the blue target, without a scratch.',focus:'A repeatable low contact and smooth delivery matter more than forcing the shot.',table:'Backspin loss depends on your cloth and the travel to the object ball. Calibrate by outcome rather than a fixed power percentage.',levels:['Short screw','Medium screw','Longer screw'],change:'The return target moves farther back.'},
{id:'cuts',name:'Cut-angle ladder',skill:'Cut potting',kind:'pot',intro:'Learn the pocket from three approach angles.',steps:['Keep the object ball in its marked position. Place the white at the selected level.','Choose the object-ball path into the pocket before getting down on the shot. Use no intentional side spin.','Play five repetitions, then use the mirrored layout for the other side.'],goal:'Pot through the highlighted corner without scratching. A jaw rattle that stays out is a miss.',focus:'Separate a line error from a pace error. Do not change both together.',table:'Rounded jaws make the real entry line important. The dashed line is a reference, not an exact pocket-acceptance prediction.',levels:['Gentle cut','Medium cut','Thinner cut'],change:'The cue ball moves sideways to increase the cut.'},
{id:'rail-v2',name:'Cushion-side potting',skill:'Rounded-pocket touch',kind:'pot',intro:'Find a reliable entry near the long cushion.',steps:['Place the object ball near, but not touching, the right cushion. Follow the grid rather than pressing it against the rail.','Use centre ball and a measured pace. Aim at the opening between the rounded jaws.','Reset both balls to the same gap from the cushion. Change only the distance when progressing.'],goal:'Pot into the highlighted corner with no scratch. Count a rejected jaw rattle as a miss.',focus:'Keep the delivery straight; avoid adding side spin to rescue the line.',table:'The diagram does not model your exact jaw opening or pocket shelf. Let clean entries on your table set the pace.',levels:['Short rail shot','Medium rail shot','Long rail shot'],change:'The object ball and cue ball move farther up the cushion.'},
{id:'side-v2',name:'Middle-pocket touch',skill:'Pocket entry',kind:'pot',intro:'Approach the middle pocket from widening angles.',steps:['Set one object ball by the marked middle-pocket approach. Use the cue-ball position for your level.','Choose a positive but controlled pace and no intentional side spin.','Keep the same positions for five shots. Mirror the next set to train the other middle pocket.'],goal:'Pot in the highlighted middle pocket without a scratch. Potting elsewhere does not count.',focus:'Do not assume the whole visible opening is available from an angle.',table:'Your rounded middle-pocket jaws need their own speed and entry-line practice; these are not American-style pocket targets.',levels:['Near square','Oblique','More oblique'],change:'The approach to the middle pocket becomes more oblique.'},
{id:'cut-stun',name:'Stun cut to a window',skill:'Advanced cut & position',kind:'control',advanced:true,intro:'Make the cut and hold the white in a small landing window.',steps:['Set the object ball and white approximately at the marked diamond positions. Choose the highlighted corner.','Use a stun-style delivery with no intended side spin. The white should move across the object-ball line, toward the blue window.','Pot and stop inside the window without touching a cushion. Pot only means the object ball went in but the position or route missed.'],goal:'Pot into the highlighted corner and stop the white’s centre inside the blue window, before touching a cushion.',focus:'Protect the pot while adjusting the white’s travel. Change pace or contact, not both at once.',table:'The blue route is a tangent-line reference for stun, not a simulated trajectory. Your actual speed, spin and throw affect the result.',levels:['Wide window','Smaller window','Tight window'],change:'The same cut stays in place while the landing window gets smaller.'},
{id:'cut-cushion',name:'One-cushion cut & return',skill:'Advanced route control',kind:'control',advanced:true,intro:'Pot the cut, use the long cushion and bring the white back into position.',steps:['Use the highlighted corner for the object ball. The blue route shows the intended approach to the right long cushion.','Start without side spin. Pot, contact that cushion once, then let the white settle in the blue window.','Count a goal only when both the pot and the one-cushion route succeed. A pot with the wrong route is Pot only.'],goal:'Pot, contact the right long cushion once, then finish the white’s centre in the blue window without touching another cushion.',focus:'First find a repeatable cushion approach. Then tune the return distance with small pace changes.',table:'The route is an idealised reference. Cushion response and spin can change the return angle; calibrate on your table rather than treating the blue line as a prediction.',levels:['Large return zone','Medium return zone','Tight return zone'],change:'The landing zone shrinks; the intended one-cushion route stays the same.'}
];
const defaults=()=>({version:2,selected:'straight-v2',profile:{objectMM:50.8,cueMM:50.8,widthMM:null,lengthMM:null},levels:{},round:null,history:[],session:null,sessionCount:0,preferences:{warmup:false,focus:'balanced'},legacy:{attempts:0,pots:0}});
const get=id=>drills.find(d=>d.id===id);
function validateProfile(p){const num=v=>v===''||v==null?null:Number(v);const out={objectMM:num(p.objectMM),cueMM:num(p.cueMM),widthMM:num(p.widthMM),lengthMM:num(p.lengthMM)};if(!Number.isFinite(out.objectMM)||out.objectMM<45||out.objectMM>60)throw Error('Object-ball diameter must be 45–60 mm.');if(out.cueMM!==null&&(!Number.isFinite(out.cueMM)||out.cueMM<40||out.cueMM>60))throw Error('Cue-ball diameter must be 40–60 mm.');if((out.widthMM===null)!==(out.lengthMM===null))throw Error('Enter both playing dimensions, or leave both blank.');if(out.widthMM!==null&&(!Number.isFinite(out.widthMM)||!Number.isFinite(out.lengthMM)||out.widthMM<800||out.widthMM>1400||out.lengthMM<1600||out.lengthMM>2800||out.lengthMM/out.widthMM<1.8||out.lengthMM/out.widthMM>2.2))throw Error('Check the cushion-nose measurements in mm; the length should be about twice the width.');return out;}
function load(raw,legacy){const d=defaults();if(!raw){if(legacy?.history){d.legacy={attempts:legacy.history.filter(h=>typeof h.pot==='boolean').length,pots:legacy.history.filter(h=>h.pot===true).length};}return d;}try{const p=validateProfile(raw.profile);d.profile=p;d.preferences={warmup:raw.preferences?.warmup===true,focus:raw.preferences?.focus==='harder'?'harder':'balanced'};d.selected=get(raw.selected)?raw.selected:'straight-v2';d.levels=Object.fromEntries(drills.map(x=>[x.id,Math.min(3,Math.max(1,Number(raw.levels?.[x.id])||1))]));d.history=Array.isArray(raw.history)?raw.history.filter(h=>h&&get(h.drill)&&['goal','pot','miss'].includes(h.result)&&typeof h.id==='string'):[];d.legacy=raw.legacy||d.legacy;d.sessionCount=Number(raw.sessionCount)||0;if(raw.round&&get(raw.round.drill)&&Array.isArray(raw.round.ids)&&raw.round.ids.length<=5&&raw.round.ids.every(id=>d.history.some(h=>h.id===id))){d.round=raw.round;d.selected=raw.round.drill;}if(raw.session&&Array.isArray(raw.session.plan)&&raw.session.plan.length===3&&raw.session.plan.every(x=>get(x.drill))&&Number.isInteger(raw.session.index)&&raw.session.index>=0&&raw.session.index<=3)d.session=raw.session;return d;}catch{return d;}}
function startRound(d,id,options={}){if(!get(id))throw Error('Unknown drill.');const level=options.level??d.levels[id]??1;if(!Number.isInteger(level)||level<1||level>3)throw Error('Level must be 1, 2 or 3.');d.selected=id;d.round={drill:id,level,mirror:!!options.mirror,guide:options.guide!==false,ids:[],sessionId:options.sessionId||null,stage:options.stage??null,profile:JSON.parse(JSON.stringify(d.profile))};return d.round;}
function attempts(d){return d.round?d.round.ids.map(id=>d.history.find(h=>h.id===id)).filter(Boolean):[];}
function recommendation(d){const r=d.round,a=attempts(d),goals=a.filter(h=>h.result==='goal').length;if(a.length<5)return r.level;return Math.min(3,Math.max(1,r.level+(goals>=4?1:goals<=1?-1:0)));}
function record(d,result){const r=d.round;if(!r||r.ids.length>=5)throw Error('This set is complete.');if(!['goal','pot','miss'].includes(result)||(result==='pot'&&get(r.drill).kind!=='control'))throw Error('Invalid result for this drill.');const id=Date.now().toString(36)+'-'+Math.random().toString(36).slice(2);d.history.push({id,drill:r.drill,level:r.level,mirror:r.mirror,result,at:Date.now(),sessionId:r.sessionId,stage:r.stage,profile:r.profile,reason:null});r.ids.push(id);return id;}
function undo(d){if(!d.round?.ids.length)return false;const id=d.round.ids.pop();d.history=d.history.filter(h=>h.id!==id);return true;}
function nextRound(d){if(attempts(d).length!==5)throw Error('Finish this set first.');const r=d.round;d.levels[r.drill]=recommendation(d);if(d.session&&r.sessionId===d.session.id){d.session.blockIds=d.session.blockIds||[[],[],[]];d.session.blockIds[r.stage]=r.ids.slice();d.session.index++;if(d.session.index===3)return false;const p=d.session.plan[d.session.index];startRound(d,p.drill,{...p,sessionId:d.session.id,stage:d.session.index});return true;}startRound(d,r.drill,{level:d.levels[r.drill],mirror:r.mirror,guide:r.guide});return true;}
function recentStats(d,id){const all=d.history.filter(h=>h.drill===id),level=d.levels[id]||1;const shots=all.filter(h=>h.level===level).slice(-10);return{shots,goals:shots.filter(h=>h.result==='goal').length,rate:shots.length?shots.filter(h=>h.result==='goal').length/shots.length:null};}
function sessionPlan(d){const used=new Set(),prefs=d.preferences||{warmup:false,focus:'balanced'},previous=d.session?.plan?.map(p=>p.drill)||[];
function pick(ids,stage){const options=ids.filter(id=>!used.has(id));const ranked=options.map((id,i)=>{const stats=recentStats(d,id),recent=previous.includes(id)?0.18:0,priority=stats.shots.length>=5?(stats.rate+recent):.55+recent+(i/options.length)*.05;return{id,stats,priority};}).sort((a,b)=>a.priority-b.priority);const v=ranked[0];used.add(v.id);return{drill:v.id,guide:stage!==2,mirror:!!(d.sessionCount%2),reason:v.stats.shots.length>=5?`${v.stats.goals}/${v.stats.shots.length} recent goals at level ${d.levels[v.id]||1}. Revisit this skill.`:`Build a baseline at level ${d.levels[v.id]||1}.`,title:['Focus','Control','Challenge'][stage]};}
const first=prefs.warmup?{drill:'delivery',guide:true,mirror:false,title:'Warm-up',reason:'Delivery warm-up is switched on.'}:pick(prefs.focus==='harder'?['cuts','rail-v2','side-v2']:['straight-v2','cuts','rail-v2','side-v2'],0);used.add(first.drill);
const advanced=['cut-stun','cut-cushion'];const control=pick(prefs.focus==='harder'?advanced:['stop','follow','draw'],1);
const ready=prefs.focus==='harder'||['cuts','stop'].some(id=>{const r=recentStats(d,id);return r.shots.length>=5&&r.rate>=.6;});
const challenge=pick(ready?[...advanced,'cuts','rail-v2','side-v2']:['cuts','rail-v2','side-v2','straight-v2'],2);if(prefs.focus==='harder'&&!advanced.includes(challenge.drill)){const alt=advanced.find(id=>!used.has(id));if(alt){challenge.drill=alt;challenge.reason='You selected harder cuts and position.';}}
return[first,control,challenge];}
function startSession(d){const plan=sessionPlan(d);d.sessionCount++;d.session={id:'session-'+Date.now()+'-'+d.sessionCount,index:0,blockIds:[[],[],[]],plan};startRound(d,plan[0].drill,{...plan[0],sessionId:d.session.id,stage:0});}
function fraction(n){const v=Math.round(n*4)/4,whole=Math.floor(v),part=['','¼','½','¾'][Math.round((v-whole)*4)];return (whole?String(whole):'')+part||'0';}
function positionLabel(p,profile,mirror=false,radius=null){const q=mirror?[4-p[0],p[1]]:p;const ro=radius??(profile.widthMM?profile.objectMM/profile.widthMM*2:.09),ky=profile.lengthMM?profile.lengthMM/profile.widthMM/2:1,diameter=profile.widthMM?profile.objectMM/profile.widthMM*4:.18;
const edges=[{gap:q[0]-ro,name:'left',axis:'x'},{gap:4-q[0]-ro,name:'right',axis:'x'},{gap:(q[1])*ky-ro,name:'top',axis:'y'},{gap:(8-q[1])*ky-ro,name:'bottom',axis:'y'}].sort((a,b)=>a.gap-b.gap);const near=edges[0],balls=Math.max(0,Math.round(near.gap/diameter*2)/2);
if(near.gap/diameter<=2){const gap=balls===0?'Almost touching':`About ${fraction(balls)} ball-width${balls===1?'':'s'} clear of`;return `${gap} the ${near.name} cushion · ${near.axis==='x'?fraction(q[1])+' diamonds down':fraction(q[0])+' diamonds across'}`;}
return `About ${fraction(q[0])} diamonds across · ${fraction(q[1])} down`;}
function layout(id,level,profile){const d=get(id);if(!d||!Number.isInteger(level)||level<1||level>3)throw Error('Invalid layout.');const ro=profile.widthMM?profile.objectMM/profile.widthMM*2:.09,rc=ro*(profile.cueMM||profile.objectMM)/profile.objectMM,gap=2*Math.sqrt(ro*rc),p=[4,0],ky=profile.lengthMM?profile.lengthMM/profile.widthMM/2:1,den=Math.hypot(1,2*ky),u=[-1/den,2/den];let o,c,z=null,gate=null,route=null;
if(id==='delivery'){c=[2,6];gate={x:2,y:6,half:[.6,.4,.22][level-1]};route=[c,[2,rc],[2,6.5]];return{c,o:null,p:null,z,gate,route,ro,rc};}
if(id==='straight-v2'){o=[4-[.7,1.1,1.5][level-1],[1.4,2.2,3][level-1]];c=[o[0]-.55*level,o[1]+1.1*level];}
if(['stop','follow','draw'].includes(id)){o=[2.5,3];const distance=id==='stop'?[1.2,2.3,3.4][level-1]:1.5;c=[o[0]+u[0]*distance,o[1]+u[1]*distance];const contact=[o[0]+u[0]*gap,o[1]+u[1]*gap];const travel=id==='stop'?0:(id==='follow'?-1:1)*[.65,1.1,1.6][level-1];z={x:contact[0]+u[0]*travel,y:contact[1]+u[1]*travel,r:id==='stop'?ro*2:[.45,.4,.35][level-1]};}
if(id==='cuts'){o=[2.8,2.4];c=[[1.4,5.8],[.8,4.6],[.7,3.1]][level-1];}
if(id==='rail-v2'){o=[3.65,[1.8,2.8,3.8][level-1]];c=[3.2,o[1]+2];}
if(id==='cut-stun'||id==='cut-cushion'){o=[2.5,2.5];c=[1,3.5];const nx=1.5,ny=-2.5*ky,nlen=Math.hypot(nx,ny),normal=[nx/nlen,ny/nlen],tangent=[-normal[1],normal[0]],g=[o[0]-normal[0]*gap,o[1]-normal[1]*gap/ky];
if(id==='cut-stun'){z={x:g[0]+tangent[0]*.95,y:g[1]+tangent[1]*.95/ky,r:[.48,.34,.23][level-1]};route=[g,[z.x,z.y]];}
else {const hitX=4-rc,travel=(hitX-g[0])/tangent[0],hitY=g[1]+tangent[1]*travel/ky,back=1.4;z={x:hitX-tangent[0]*back,y:hitY+tangent[1]*back/ky,r:[.6,.43,.28][level-1]};route=[g,[hitX,hitY],[z.x,z.y]];}}
if(id==='side-v2'){o=[[2.8,4.15],[2.8,4.5],[2.8,4.9]][level-1];c=[1,5.8];p[1]=4;}
return{c,o,p,z,gate,route,ro,rc};}
const api={drills,defaults,get,load,validateProfile,startRound,attempts,recommendation,record,undo,nextRound,startSession,sessionPlan,recentStats,fraction,positionLabel,layout};if(typeof module!=='undefined')module.exports=api;else root.Trainer=api;
})(typeof window!=='undefined'?window:globalThis);
